CREATE TABLE STORY(
ID NUMBER,
CONSTRAINT STORY_ID PRIMARY KEY(ID),
FLIGHT NUMBER,
CONSTRAINT FLT_FK FOREIGN KEY(FLIGHT)
REFERENCES FLIGHT(ID),
PASSENGER NUMBER,
CONSTRAINT PSN_FK FOREIGN KEY(PASSENGER)
REFERENCES PASSENGER(ID));