CREATE TABLE FLIGHT(
ID NUMBER,
CONSTRAINT FLIGHT_ID PRIMARY KEY(ID),
PLANE NUMBER,
CONSTRAINT FLIGHT_FK FOREIGN KEY(PLANE)
REFERENCES PLANE(ID),
DATE_FLIGHT DATE,
CITY_FROM VARCHAR2(50),
CITY_TO VARCHAR2(50));